# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Fabric API
fabric_version=0.116.1+1.21.1

# Mod Properties
mod_id=carpet-bot-restriction
mod_version=1.1.1
maven_group=carpetbotrestriction
archives_base_name=carpet-bot-restriction

# Dependencies
carpet_core_version=1.21-1.4.147+v240613
fpa_version=0.3.3